source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.2.0'

# Core Rails
gem 'rails', '~> 7.1.0'

# Database
gem 'pg', '~> 1.5'

# Web server
gem 'puma', '~> 6.0'

# Asset pipeline
gem 'sprockets-rails'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'

# UI
gem 'bootstrap', '~> 5.3'
gem 'sassc-rails'

# Authentication
gem 'bcrypt', '~> 3.1.7'

# API client
gem 'faraday', '~> 2.7'
gem 'faraday-retry'

# Background jobs
gem 'redis', '~> 5.0'
gem 'sidekiq', '~> 7.0'

# Utilities
gem 'jbuilder'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Production
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
end

group :development do
  gem 'web-console'
end
