# golangci-lint configuration for Go backend
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type check
    - unused        # Find unused code
    - gofmt         # Format check
    - goimports     # Imports check
    - misspell      # Spell check
    - gocritic      # Go critique
    - revive        # Fast linter
    - gosec         # Security check
    - bodyclose     # Check HTTP body closed
    - noctx         # Check for sending HTTP requests without context
    - rowserrcheck  # Check SQL rows.Err
    - sqlclosecheck # Check SQL Close
    - wastedassign  # Find wasted assignments

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    # Ignore common defer patterns
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close
      - (*database/sql.DB).Close

  govet:
    check-shadowing: false
    enable-all: false
    enable:
      - atomic
      - bools
      - errorsas
      - nilfunc
      - printf

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/GezzyDax/timelith,github.com/GezzyDax/Timelith

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: exported
        disabled: true  # Disable for now

  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G307 # Deferring unsafe method (false positives)
      - G114 # Use of net/http serve function

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - govet

    # Exclude defer Close errors (common pattern)
    - text: "Error return value of.*Close.*is not checked"
      linters:
        - errcheck

    # Exclude logger sync errors
    - text: "Error return value of.*Sync.*is not checked"
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 3
  new: false

output:
  sort-results: true
